# Generated by Django 4.1.3 on 2022-11-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_shoppingitem_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.shoppinglist'),
        ),
    ]
