# Generated by Django 4.1.3 on 2022-11-14 13:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_alter_shoppingitem_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gui.shoppinglist'),
        ),
    ]
