# Generated by Django 4.1.3 on 2022-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_alter_shoppingitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
